// <auto-generated />
using System;
using BuildyBackend.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildyBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240328230655_migracion")]
    partial class migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.CityDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimCityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceDSId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceDSId");

                    b.ToTable("CityDS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6412),
                            Name = "Melo",
                            NominatimCityCode = "ME",
                            ProvinceDSId = 1,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6413)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6414),
                            Name = "Montevideo",
                            NominatimCityCode = "MO",
                            ProvinceDSId = 2,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6415)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.CountryDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CountryDS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6049),
                            Name = "Uruguay",
                            NominatimCountryCode = "UY",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6055)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityDSId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstateIsRented")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleMapsURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerDSId")
                        .HasColumnType("int");

                    b.Property<int?>("PresentRentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityDSId");

                    b.HasIndex("OwnerDSId");

                    b.ToTable("Estate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Colón 476",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6566),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+476,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674814,-54.1757085,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b6fbe707:0x3f99b6b98961385b!8m2!3d-32.3674814!4d-54.1731282!16s%2Fg%2F11fn9p0pws?hl=es-419&entry=ttu",
                            LatLong = "-32.3674814,-54.1757085",
                            Name = "Colón 476",
                            OwnerDSId = 3,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6566)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Colón 480",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6618),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+480,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674762,-54.1755751,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b0c5f12b:0xaf5b5ba2ea4eb1cb!8m2!3d-32.3674762!4d-54.1729948!16s%2Fg%2F11rz98nq5_?hl=es-419&entry=ttu",
                            LatLong = "-32.3674762,-54.1755751",
                            Name = "Colón 480",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6619)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Colón 491",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6621),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+491,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.367241,-54.1754153,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b180e29b:0x95542a9eb2345b16!8m2!3d-32.367241!4d-54.172835!16s%2Fg%2F11fctc9z9z?hl=es-419&entry=ttu",
                            LatLong = "-32.367241,-54.1754153",
                            Name = "Colón 491",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6622)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Colón 495",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6624),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+495,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3672195,-54.1755857,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b3f659db:0xf3c82a67cd3ebe76!8m2!3d-32.3672195!4d-54.1730054!16s%2Fg%2F11gmz50cjj?hl=es-419&entry=ttu",
                            LatLong = "-32.3672195,-54.1755857",
                            Name = "Colón 495",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6624)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Colón 503",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6628),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+503,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3672809,-54.1751337,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980a659bd3f:0x1f64283da64670a9!8m2!3d-32.3672809!4d-54.1725534?hl=es-419&entry=ttu",
                            LatLong = "-32.3672809,-54.1751337",
                            Name = "Colón 503",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6635)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Darío Silva 774",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6643),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+774,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3679807,-54.1752022,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980a2c60edb:0x48ad692931a026ea!8m2!3d-32.3679807!4d-54.1726219!16s%2Fg%2F11gr6dzf3g?hl=es-419&entry=ttu",
                            LatLong = "-32.3679807,-54.1752022",
                            Name = "Darío Silva 774",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6643)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Darío Silva 774 BIS",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6644),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+774,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3679807,-54.1752022,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980a2c60edb:0x48ad692931a026ea!8m2!3d-32.3679807!4d-54.1726219!16s%2Fg%2F11gr6dzf3g?hl=es-419&entry=ttu",
                            LatLong = "-32.3679807,-54.1752022",
                            Name = "Darío Silva 774 BIS",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6645)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Darío Silva 781",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6646),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+781,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3675191,-54.1753876,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b076246d:0x1b122d0ac3c1dbc7!8m2!3d-32.3675191!4d-54.1728073!16s%2Fg%2F11g194j1tj?hl=es-419&entry=ttu",
                            LatLong = "-32.3675191,-54.1753876",
                            Name = "Darío Silva 781",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6647)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Darío Silva 785",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6652),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+785,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3676402,-54.1754579,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ba5f73d1:0x186b45d8ed124b2a!8m2!3d-32.3676402!4d-54.1728776!16s%2Fg%2F11sb62lb6c?hl=es-419&entry=ttu",
                            LatLong = "-32.3676402,-54.1754579",
                            Name = "Darío Silva 785",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6652)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Darío Silva 789",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6654),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+789,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3676919,-54.1754685,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ba535f25:0xbdc6468d3ed51cc1!8m2!3d-32.3676919!4d-54.1728882!16s%2Fg%2F11syz1ryh9?hl=es-419&entry=ttu",
                            LatLong = "-32.3676919,-54.1754685",
                            Name = "Darío Silva 789",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6654)
                        },
                        new
                        {
                            Id = 11,
                            Address = "Darío Silva 793",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6656),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+793,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3675108,-54.1754001,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b079be31:0xa19a7a3d822a0595!8m2!3d-32.3675108!4d-54.1728198!16s%2Fg%2F11h_c4rxz9?hl=es-419&entry=ttu",
                            LatLong = "-32.3675108,-54.1754001",
                            Name = "Darío Silva 793",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6656)
                        },
                        new
                        {
                            Id = 12,
                            Address = "Darío Silva 801",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6658),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+801,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3673741,-54.1752804,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980ad44ba05:0x3da437edd983606!8m2!3d-32.3673741!4d-54.1727001?hl=es-419&entry=ttu",
                            LatLong = "-32.3673741,-54.1752804",
                            Name = "Darío Silva 801",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6658)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Darío Silva 803",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6660),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+803,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3673108,-54.1755231,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980ad44ba05:0x24b5f3fc904ac228!8m2!3d-32.3673108!4d-54.1729428?hl=es-419&entry=ttu",
                            LatLong = "-32.3673108,-54.1755231",
                            Name = "Darío Silva 803",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6660)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Darío Silva Cochera",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6662),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+476,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674814,-54.1757085,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b6fbe707:0x3f99b6b98961385b!8m2!3d-32.3674814!4d-54.1731282!16s%2Fg%2F11fn9p0pws?hl=es-419&entry=ttu",
                            LatLong = "-32.3674814,-54.1757085",
                            Name = "Darío Silva Cochera",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6662)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Treinta y Tres 299",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6849),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Treinta+y+Tres+299,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3765821,-54.1703877,17z/data=!3m1!4b1!4m6!3m5!1s0x95092bd6c1beccc3:0xb91b3165ec6107e3!8m2!3d-32.3765821!4d-54.1678074!16s%2Fg%2F11gmz7h_cl?hl=es-419&entry=ttu",
                            LatLong = "-32.3765821,-54.1703877",
                            Name = "Treinta y Tres 299",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6849)
                        },
                        new
                        {
                            Id = 16,
                            Address = "Manuel Oribe 788",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6851),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Gral.+Manuel+Oribe+788,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3764414,-54.1706063,17z/data=!3m1!4b1!4m6!3m5!1s0x95092bd69533354f:0xd6a6a68977288372!8m2!3d-32.3764414!4d-54.168026!16s%2Fg%2F11h57sb583?hl=es-419&entry=ttu",
                            LatLong = "-32.3764414,-54.1706063",
                            Name = "Manuel Oribe 788",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6851)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Rincón Artigas 702",
                            CityDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6853),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Dr+Rincon+Artigas+702,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3690096,-54.176412,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ee49a557:0xfbaefe3d055f9ab9!8m2!3d-32.3690096!4d-54.1738317!16s%2Fg%2F11h_c4zxvw?hl=es-419&entry=ttu",
                            LatLong = "-32.3690096,-54.176412",
                            Name = "Rincón Artigas 702",
                            OwnerDSId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6853)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Maldonado 1106",
                            CityDSId = 2,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6855),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Maldonado+1106,+11100+Montevideo,+Departamento+de+Montevideo/@-34.9097969,-56.1945273,17z/data=!3m1!4b1!4m6!3m5!1s0x959f81c066a6fb4d:0xdb3d1d7d172a0f4c!8m2!3d-34.9097969!4d-56.191947!16s%2Fg%2F11fhvn7njf?hl=es-419&entry=ttu",
                            LatLong = "-34.9097969,-56.1945273",
                            Name = "Maldonado 1106",
                            OwnerDSId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6855)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.File1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RentId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LabourCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.OwnerDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OwnerDS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "violet",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6482),
                            Name = "Mirta",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6483)
                        },
                        new
                        {
                            Id = 2,
                            Color = "orange",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6484),
                            Name = "Gladys",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6484)
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6485),
                            Name = "Cristina",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6485)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReportId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.ProvinceDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryDSId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimProvinceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryDSId");

                    b.ToTable("ProvinceDS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6346),
                            Name = "Cerro Largo",
                            NominatimProvinceCode = "CL",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6346)
                        },
                        new
                        {
                            Id = 2,
                            CountryDSId = 1,
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6348),
                            Name = "Montevideo",
                            NominatimProvinceCode = "MO",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 289, DateTimeKind.Local).AddTicks(6348)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datetime_monthInit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrimaryTenantId")
                        .HasColumnType("int");

                    b.Property<bool>("RentIsEnded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warrant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("BuildyBackend.Core.Helpers.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "role",
                            ClaimValue = "Admin",
                            UserId = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "e0765c93-676c-4199-b7ee-d7877c471821"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "58fbedfc-e682-479b-ba46-19ef4c137d2a"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "e0765c93-676c-4199-b7ee-d7877c471821",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "58fbedfc-e682-479b-ba46-19ef4c137d2a",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.IdentityEntities.BuildyRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("BuildyRole");

                    b.HasData(
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(6626),
                            Update = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(6628)
                        },
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a3f2-e1a901f6811c",
                            Name = "User",
                            NormalizedName = "USER",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(6635),
                            Update = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(6636)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.IdentityEntities.BuildyUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("BuildyUser");

                    b.HasData(
                        new
                        {
                            Id = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bb3dfb17-54ca-4627-9096-dd2bfd1a637b",
                            Email = "admin@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BUILDY.LAT",
                            NormalizedUserName = "USERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEeva5gGNj1QmTOm/Hpo5K6FpOXZcuty9DNpWNjDiWbxF/ZaEsVUDktiALQbdTSD6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "856e253e-d410-4fde-ab70-c38e5f5eb6a1",
                            TwoFactorEnabled = false,
                            UserName = "useradmin",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(7186),
                            Name = "Usuario administrador",
                            Update = new DateTime(2024, 3, 28, 20, 6, 54, 939, DateTimeKind.Local).AddTicks(7188)
                        },
                        new
                        {
                            Id = "e0765c93-676c-4199-b7ee-d7877c471821",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0ffa4c2-001b-4a95-9357-88f46cef9bce",
                            Email = "normal@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NORMAL@BUILDY.LAT",
                            NormalizedUserName = "USERNORMAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEAisVtkqGZTEV7zEVtLHCw2beEe8r/Fs9a+9o1/C3ZrMp4XY54AhKZgqqPldSrz5dw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae259a4a-5d52-4168-9270-44b0c55973ad",
                            TwoFactorEnabled = false,
                            UserName = "usernormal",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 29, DateTimeKind.Local).AddTicks(7978),
                            Name = "Usuario normal",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 29, DateTimeKind.Local).AddTicks(7995)
                        },
                        new
                        {
                            Id = "58fbedfc-e682-479b-ba46-19ef4c137d2a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e3708b2-12f7-4ef6-bd44-bb8bc59a3345",
                            Email = "mirta@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIRTA@BUILDY.LAT",
                            NormalizedUserName = "MIRTADLS",
                            PasswordHash = "AQAAAAIAAYagAAAAENsd35tT246uiUfBI4Q4m+lHVC770QOPLXhAN0u+QG5r17l+99etGc2llsaNDwsbrQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c0f6160-f9b9-40ae-98a4-04d006b80817",
                            TwoFactorEnabled = false,
                            UserName = "mirtadls",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 121, DateTimeKind.Local).AddTicks(3532),
                            Name = "Mirta de los Santos",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 121, DateTimeKind.Local).AddTicks(3538)
                        },
                        new
                        {
                            Id = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9cdfc15-94c1-4511-a1ab-3638d4000737",
                            Email = "gladys@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GLADYS@BUILDY.LAT",
                            NormalizedUserName = "IRGLA",
                            PasswordHash = "AQAAAAIAAYagAAAAEEUcEER3PxEFGFM9jbPLKFqU8OPVLYElPuBnAFkeo/Os4ff3m0LRhFu0vGlDfCeaiQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74dc8fd1-b955-4c02-9f5d-058a37521be3",
                            TwoFactorEnabled = false,
                            UserName = "irgla",
                            Creation = new DateTime(2024, 3, 28, 20, 6, 55, 203, DateTimeKind.Local).AddTicks(7066),
                            Name = "Gladys de los Santos",
                            Update = new DateTime(2024, 3, 28, 20, 6, 55, 203, DateTimeKind.Local).AddTicks(7073)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.CityDS", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.ProvinceDS", "ProvinceDS")
                        .WithMany()
                        .HasForeignKey("ProvinceDSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvinceDS");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.CityDS", "CityDS")
                        .WithMany()
                        .HasForeignKey("CityDSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildyBackend.Core.Domain.Entities.OwnerDS", "OwnerDS")
                        .WithMany()
                        .HasForeignKey("OwnerDSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityDS");

                    b.Navigation("OwnerDS");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.File1", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Rent", "Rent")
                        .WithMany("ListFiles")
                        .HasForeignKey("RentId");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListJobs")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Job", "Job")
                        .WithMany("ListPhotos")
                        .HasForeignKey("JobId");

                    b.HasOne("BuildyBackend.Core.Domain.Entities.Report", "Report")
                        .WithMany("ListPhotos")
                        .HasForeignKey("ReportId");

                    b.Navigation("Job");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.ProvinceDS", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.CountryDS", "CountryDS")
                        .WithMany()
                        .HasForeignKey("CountryDSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryDS");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListRents")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListReports")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Rent", "Rent")
                        .WithMany("ListTenants")
                        .HasForeignKey("RentId");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Worker", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Job", "Job")
                        .WithMany("ListWorkers")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.Navigation("ListJobs");

                    b.Navigation("ListRents");

                    b.Navigation("ListReports");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.Navigation("ListPhotos");

                    b.Navigation("ListWorkers");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.Navigation("ListFiles");

                    b.Navigation("ListTenants");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.Navigation("ListPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
