// <auto-generated />
using System;
using BuildyBackend.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildyBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240401030631_migracion")]
    partial class migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimCityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6838),
                            Name = "Melo",
                            NominatimCityCode = "ME",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6841)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6844),
                            Name = "Montevideo",
                            NominatimCityCode = "MO",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6844)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6579),
                            Name = "Uruguay",
                            NominatimCountryCode = "UY",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6597)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstateIsRented")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleMapsURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PresentRentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Estate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Colón 476",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7005),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+476,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674814,-54.1757085,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b6fbe707:0x3f99b6b98961385b!8m2!3d-32.3674814!4d-54.1731282!16s%2Fg%2F11fn9p0pws?hl=es-419&entry=ttu",
                            LatLong = "-32.3674814,-54.1757085",
                            Name = "Colón 476",
                            OwnerId = 3,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7008)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Colón 480",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7023),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+480,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674762,-54.1755751,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b0c5f12b:0xaf5b5ba2ea4eb1cb!8m2!3d-32.3674762!4d-54.1729948!16s%2Fg%2F11rz98nq5_?hl=es-419&entry=ttu",
                            LatLong = "-32.3674762,-54.1755751",
                            Name = "Colón 480",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7023)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Colón 491",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7028),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+491,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.367241,-54.1754153,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b180e29b:0x95542a9eb2345b16!8m2!3d-32.367241!4d-54.172835!16s%2Fg%2F11fctc9z9z?hl=es-419&entry=ttu",
                            LatLong = "-32.367241,-54.1754153",
                            Name = "Colón 491",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7029)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Colón 495",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7034),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+495,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3672195,-54.1755857,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b3f659db:0xf3c82a67cd3ebe76!8m2!3d-32.3672195!4d-54.1730054!16s%2Fg%2F11gmz50cjj?hl=es-419&entry=ttu",
                            LatLong = "-32.3672195,-54.1755857",
                            Name = "Colón 495",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7034)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Colón 503",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7039),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+503,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3672809,-54.1751337,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980a659bd3f:0x1f64283da64670a9!8m2!3d-32.3672809!4d-54.1725534?hl=es-419&entry=ttu",
                            LatLong = "-32.3672809,-54.1751337",
                            Name = "Colón 503",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7040)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Darío Silva 774",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7042),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+774,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3679807,-54.1752022,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980a2c60edb:0x48ad692931a026ea!8m2!3d-32.3679807!4d-54.1726219!16s%2Fg%2F11gr6dzf3g?hl=es-419&entry=ttu",
                            LatLong = "-32.3679807,-54.1752022",
                            Name = "Darío Silva 774",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7043)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Darío Silva 774 BIS",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7047),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+774,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3679807,-54.1752022,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980a2c60edb:0x48ad692931a026ea!8m2!3d-32.3679807!4d-54.1726219!16s%2Fg%2F11gr6dzf3g?hl=es-419&entry=ttu",
                            LatLong = "-32.3679807,-54.1752022",
                            Name = "Darío Silva 774 BIS",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Darío Silva 781",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7051),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+781,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3675191,-54.1753876,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b076246d:0x1b122d0ac3c1dbc7!8m2!3d-32.3675191!4d-54.1728073!16s%2Fg%2F11g194j1tj?hl=es-419&entry=ttu",
                            LatLong = "-32.3675191,-54.1753876",
                            Name = "Darío Silva 781",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7052)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Darío Silva 785",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7055),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+785,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3676402,-54.1754579,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ba5f73d1:0x186b45d8ed124b2a!8m2!3d-32.3676402!4d-54.1728776!16s%2Fg%2F11sb62lb6c?hl=es-419&entry=ttu",
                            LatLong = "-32.3676402,-54.1754579",
                            Name = "Darío Silva 785",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7055)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Darío Silva 789",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7059),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+789,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3676919,-54.1754685,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ba535f25:0xbdc6468d3ed51cc1!8m2!3d-32.3676919!4d-54.1728882!16s%2Fg%2F11syz1ryh9?hl=es-419&entry=ttu",
                            LatLong = "-32.3676919,-54.1754685",
                            Name = "Darío Silva 789",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7059)
                        },
                        new
                        {
                            Id = 11,
                            Address = "Darío Silva 793",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7063),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+793,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3675108,-54.1754001,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b079be31:0xa19a7a3d822a0595!8m2!3d-32.3675108!4d-54.1728198!16s%2Fg%2F11h_c4rxz9?hl=es-419&entry=ttu",
                            LatLong = "-32.3675108,-54.1754001",
                            Name = "Darío Silva 793",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7064)
                        },
                        new
                        {
                            Id = 12,
                            Address = "Darío Silva 801",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7066),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+801,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3673741,-54.1752804,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980ad44ba05:0x3da437edd983606!8m2!3d-32.3673741!4d-54.1727001?hl=es-419&entry=ttu",
                            LatLong = "-32.3673741,-54.1752804",
                            Name = "Darío Silva 801",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7067)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Darío Silva 803",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7071),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Calle+Dr.+Juan+Dar%C3%ADo+Silva+803,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3673108,-54.1755231,17z/data=!3m1!4b1!4m5!3m4!1s0x95092980ad44ba05:0x24b5f3fc904ac228!8m2!3d-32.3673108!4d-54.1729428?hl=es-419&entry=ttu",
                            LatLong = "-32.3673108,-54.1755231",
                            Name = "Darío Silva 803",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7071)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Darío Silva Cochera",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7074),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Col%C3%B3n+476,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3674814,-54.1757085,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980b6fbe707:0x3f99b6b98961385b!8m2!3d-32.3674814!4d-54.1731282!16s%2Fg%2F11fn9p0pws?hl=es-419&entry=ttu",
                            LatLong = "-32.3674814,-54.1757085",
                            Name = "Darío Silva Cochera",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7074)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Treinta y Tres 299",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7078),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Treinta+y+Tres+299,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3765821,-54.1703877,17z/data=!3m1!4b1!4m6!3m5!1s0x95092bd6c1beccc3:0xb91b3165ec6107e3!8m2!3d-32.3765821!4d-54.1678074!16s%2Fg%2F11gmz7h_cl?hl=es-419&entry=ttu",
                            LatLong = "-32.3765821,-54.1703877",
                            Name = "Treinta y Tres 299",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7078)
                        },
                        new
                        {
                            Id = 16,
                            Address = "Manuel Oribe 788",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7082),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/C.+Gral.+Manuel+Oribe+788,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3764414,-54.1706063,17z/data=!3m1!4b1!4m6!3m5!1s0x95092bd69533354f:0xd6a6a68977288372!8m2!3d-32.3764414!4d-54.168026!16s%2Fg%2F11h57sb583?hl=es-419&entry=ttu",
                            LatLong = "-32.3764414,-54.1706063",
                            Name = "Manuel Oribe 788",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7084)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Rincón Artigas 702",
                            CityId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7146),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Dr+Rincon+Artigas+702,+37000+Melo,+Departamento+de+Cerro+Largo/@-32.3690096,-54.176412,17z/data=!3m1!4b1!4m6!3m5!1s0x95092980ee49a557:0xfbaefe3d055f9ab9!8m2!3d-32.3690096!4d-54.1738317!16s%2Fg%2F11h_c4zxvw?hl=es-419&entry=ttu",
                            LatLong = "-32.3690096,-54.176412",
                            Name = "Rincón Artigas 702",
                            OwnerId = 2,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7149)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Maldonado 1106",
                            CityId = 2,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7155),
                            EstateIsRented = false,
                            GoogleMapsURL = "https://www.google.com/maps/place/Maldonado+1106,+11100+Montevideo,+Departamento+de+Montevideo/@-34.9097969,-56.1945273,17z/data=!3m1!4b1!4m6!3m5!1s0x959f81c066a6fb4d:0xdb3d1d7d172a0f4c!8m2!3d-34.9097969!4d-56.191947!16s%2Fg%2F11fhvn7njf?hl=es-419&entry=ttu",
                            LatLong = "-34.9097969,-56.1945273",
                            Name = "Maldonado 1106",
                            OwnerId = 1,
                            PresentRentId = 0,
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(7156)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.File1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RentId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LabourCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "violet",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6920),
                            Name = "Mirta",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6921)
                        },
                        new
                        {
                            Id = 2,
                            Color = "orange",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6923),
                            Name = "Gladys",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6924)
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6927),
                            Name = "Cristina",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6927)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReportId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NominatimProvinceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6755),
                            Name = "Cerro Largo",
                            NominatimProvinceCode = "CL",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6758),
                            Name = "Montevideo",
                            NominatimProvinceCode = "MO",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 652, DateTimeKind.Local).AddTicks(6761)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datetime_monthInit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrimaryTenantId")
                        .HasColumnType("int");

                    b.Property<bool>("RentIsEnded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warrant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("BuildyBackend.Core.Helpers.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "role",
                            ClaimValue = "Admin",
                            UserId = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "e0765c93-676c-4199-b7ee-d7877c471821"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "58fbedfc-e682-479b-ba46-19ef4c137d2a"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "role",
                            ClaimValue = "User",
                            UserId = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "e0765c93-676c-4199-b7ee-d7877c471821",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "58fbedfc-e682-479b-ba46-19ef4c137d2a",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.IdentityEntities.BuildyRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("BuildyRole");

                    b.HasData(
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(3824),
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(3827)
                        },
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a3f2-e1a901f6811c",
                            Name = "User",
                            NormalizedName = "USER",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(3848),
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(3850)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.IdentityEntities.BuildyUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("BuildyUser");

                    b.HasData(
                        new
                        {
                            Id = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e5f083a-2355-4d9b-928a-cfe58d1cef3c",
                            Email = "admin@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BUILDY.LAT",
                            NormalizedUserName = "USERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPl1JxEEAeOJ+iY2BX425JDgh0UvWCBqCMKzn3b/kihsREcDPZAGPf1LsLGes3aB0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "67071d7f-0a28-4661-a913-64bc01bf0c0a",
                            TwoFactorEnabled = false,
                            UserName = "useradmin",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(4677),
                            Name = "Usuario administrador",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 69, DateTimeKind.Local).AddTicks(4680)
                        },
                        new
                        {
                            Id = "e0765c93-676c-4199-b7ee-d7877c471821",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0b11bfc-b55c-447c-aada-8bf881df7030",
                            Email = "normal@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NORMAL@BUILDY.LAT",
                            NormalizedUserName = "USERNORMAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOcsraTXmDSZT+bVrLpJPpI5TL+UQUs550DwubyAz5hLnn7merchCClgms9Ug5IEqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb1e4432-a51a-46c4-b690-ee42376f715c",
                            TwoFactorEnabled = false,
                            UserName = "usernormal",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 246, DateTimeKind.Local).AddTicks(8248),
                            Name = "Usuario normal",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 246, DateTimeKind.Local).AddTicks(8265)
                        },
                        new
                        {
                            Id = "58fbedfc-e682-479b-ba46-19ef4c137d2a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78cdaedf-5e32-49c8-8137-b33d107e9334",
                            Email = "mirta@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIRTA@BUILDY.LAT",
                            NormalizedUserName = "MIRTADLS",
                            PasswordHash = "AQAAAAIAAYagAAAAEEbg86FvCQmgCmoPx7tnH8Z4MFSsnipu5AKYvbdrvbVGp5/I/0XkjjLHwV/ISW1XSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4315ebe-5aa4-4693-92f8-760fa30bcf1e",
                            TwoFactorEnabled = false,
                            UserName = "mirtadls",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 377, DateTimeKind.Local).AddTicks(1840),
                            Name = "Mirta de los Santos",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 377, DateTimeKind.Local).AddTicks(1861)
                        },
                        new
                        {
                            Id = "11c767dc-e8ce-448e-8fdb-ee590a44a3ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47b97e1a-e303-4324-8095-bc713244afd2",
                            Email = "gladys@buildy.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GLADYS@BUILDY.LAT",
                            NormalizedUserName = "IRGLA",
                            PasswordHash = "AQAAAAIAAYagAAAAEMJISL50U2Cm6RVYBr92VYA5+97zEoo/8xuE5J6Lkmw1oavdSiaNyEaGT6lOocGirQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a4e048b1-666e-4093-a53c-857979a128e2",
                            TwoFactorEnabled = false,
                            UserName = "irgla",
                            Creation = new DateTime(2024, 4, 1, 0, 6, 27, 537, DateTimeKind.Local).AddTicks(4609),
                            Name = "Gladys de los Santos",
                            Update = new DateTime(2024, 4, 1, 0, 6, 27, 537, DateTimeKind.Local).AddTicks(4622)
                        });
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.City", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildyBackend.Core.Domain.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.File1", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Rent", "Rent")
                        .WithMany("ListFiles")
                        .HasForeignKey("RentId");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListJobs")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Job", "Job")
                        .WithMany("ListPhotos")
                        .HasForeignKey("JobId");

                    b.HasOne("BuildyBackend.Core.Domain.Entities.Report", "Report")
                        .WithMany("ListPhotos")
                        .HasForeignKey("ReportId");

                    b.Navigation("Job");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Province", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListRents")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Estate", "Estate")
                        .WithMany("ListReports")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Rent", "Rent")
                        .WithMany("ListTenants")
                        .HasForeignKey("RentId");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Worker", b =>
                {
                    b.HasOne("BuildyBackend.Core.Domain.Entities.Job", "Job")
                        .WithMany("ListWorkers")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Estate", b =>
                {
                    b.Navigation("ListJobs");

                    b.Navigation("ListRents");

                    b.Navigation("ListReports");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Job", b =>
                {
                    b.Navigation("ListPhotos");

                    b.Navigation("ListWorkers");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Rent", b =>
                {
                    b.Navigation("ListFiles");

                    b.Navigation("ListTenants");
                });

            modelBuilder.Entity("BuildyBackend.Core.Domain.Entities.Report", b =>
                {
                    b.Navigation("ListPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
